server:
  port: 8001

eureka:
  instance:
    hostname: 10.8.50.11
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/